<?php

namespace AppBundle\Repository;

/**
 * CrtInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrtInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
