<?php

namespace AppBundle\Repository;

/**
 * InfoCrtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoCrtRepository extends \Doctrine\ORM\EntityRepository
{
}
