<?php

namespace AppBundle\Repository;

/**
 * jourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jourRepository extends \Doctrine\ORM\EntityRepository
{
}
